services:
  vpn-server:
    image: qmcgaw/gluetun
    platform: linux/amd64
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - OPENVPN_USER=REDACTED_USER
      - OPENVPN_PASSWORD=REDACTED_PASSWORD
      - FREE_ONLY=on
      - SERVER_COUNTRIES="United States"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - "8888:8080"  # For the streaming service
      - "9090:9090"  # Expose the streaming port
    healthcheck:
      test: ["CMD", "ping", "-c", "3", "127.0.0.1:8080"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  restreamer:
    image: quay.io/galexrt/vlc
    command: stations/1010-wins.m3u --sout '#standard{access=http,mux=ts,dst=:9090}' --loop
    platform: linux/amd64
    volumes:
      - ./stations:/data/stations
    depends_on:
      vpn-server:
        condition: service_healthy
        restart: true
    network_mode: service:vpn-server  # Use the VPN container's network
